conda-forge/sunpy-feedstock

- recipe/meta.yaml
It's probably a good idea to run the whole offline test suite.
> Add sunpy tests

- recipe/meta.yaml
This will test if the bug with SciPy is fixed.
> Unpin MKL version for Windows.

- recipe/meta.yaml
With the new glymur update, it has been re-added to SunPy due to a bug having been fixed.
> [0.7] Release of 0.7.8 with Conda Glymur 

- appveyor.yml
- recipe/meta.yaml
> release v0.8.3

- .azure-pipelines/azure-pipelines-osx.yml
- .azure-pipelines/azure-pipelines-win.yml
- recipe/meta.yaml
@conda-forge-admin please rerender
> bump to 1.1.1

- .azure-pipelines/azure-pipelines-linux.yml
- .azure-pipelines/azure-pipelines-osx.yml
- .azure-pipelines/azure-pipelines-win.yml
- .ci_support/linux_python3.6.____cpython.yaml
- .ci_support/linux_python3.7.____cpython.yaml
- .ci_support/linux_python3.8.____cpython.yaml
- .ci_support/osx_python3.6.____cpython.yaml
- .ci_support/osx_python3.7.____cpython.yaml
- .ci_support/osx_python3.8.____cpython.yaml
- .ci_support/win_python3.6.____cpython.yaml
- .ci_support/win_python3.7.____cpython.yaml
- .ci_support/win_python3.8.____cpython.yaml
- README.md
- recipe/meta.yaml
> Bump to 1.0.9

- .azure-pipelines/azure-pipelines-osx.yml
- .azure-pipelines/azure-pipelines-win.yml
- .scripts/build_steps.sh
- .scripts/run_docker_build.sh
- .scripts/run_osx_build.sh
- README.md
- recipe/meta.yaml
> release 1.0.10

- recipe/meta.yaml
> Update to 2.0.8

- recipe/meta.yaml
> Upgrade to 3.0.0 and pin all min version

- recipe/meta.yaml
> Add dstansby as recipe maintainer

- .azure-pipelines/azure-pipelines-linux.yml
- .azure-pipelines/azure-pipelines-osx.yml
- .azure-pipelines/azure-pipelines-win.yml
- .ci_support/linux_64_numpy1.18python3.7.____cpython.yaml
- .ci_support/linux_64_numpy1.18python3.8.____cpython.yaml
- .ci_support/linux_64_numpy1.19python3.9.____cpython.yaml
- .gitattributes
- .scripts/build_steps.sh
- .scripts/run_docker_build.sh
- .scripts/run_osx_build.sh
- README.md
- build-locally.py
- recipe/meta.yaml
> update to v3.0.3

- .azure-pipelines/azure-pipelines-linux.yml
- .azure-pipelines/azure-pipelines-osx.yml
- .azure-pipelines/azure-pipelines-win.yml
- .ci_support/linux_64_numpy1.21python3.10.____cpython.yaml
- .ci_support/migrations/python310.yaml
- .ci_support/osx_64_numpy1.21python3.10.____cpython.yaml
- .ci_support/win_64_numpy1.21python3.10.____cpython.yaml
- README.md
- recipe/meta.yaml
> Rebuild 3.1.x for python310

- .azure-pipelines/azure-pipelines-linux.yml
- .azure-pipelines/azure-pipelines-osx.yml
- .azure-pipelines/azure-pipelines-win.yml
- .ci_support/linux_64_numpy1.21python3.10.____cpython.yaml
- .ci_support/migrations/python310.yaml
- .ci_support/osx_64_numpy1.21python3.10.____cpython.yaml
- .ci_support/win_64_numpy1.21python3.10.____cpython.yaml
- README.md
- recipe/meta.yaml
> Rebuild 3.0.x for python310

- .azure-pipelines/azure-pipelines-win.yml
- .scripts/build_steps.sh
- .scripts/run_osx_build.sh
- recipe/meta.yaml
> sunpy v3.1.3

- .azure-pipelines/azure-pipelines-win.yml
- .scripts/build_steps.sh
- .scripts/run_osx_build.sh
- recipe/meta.yaml
> sunpy v3.0.4

- .github/CODEOWNERS
- README.md
- recipe/meta.yaml
> Remove Steve from recipe maintainers

- .azure-pipelines/azure-pipelines-linux.yml
- .azure-pipelines/azure-pipelines-osx.yml
- .azure-pipelines/azure-pipelines-win.yml
- .ci_support/linux_64_numpy1.19python3.7.____cpython.yaml
- .ci_support/linux_64_numpy1.19python3.8.____cpython.yaml
- .ci_support/osx_64_numpy1.19python3.7.____cpython.yaml
- .ci_support/osx_64_numpy1.19python3.8.____cpython.yaml
- .ci_support/win_64_numpy1.19python3.7.____cpython.yaml
- .ci_support/win_64_numpy1.19python3.8.____cpython.yaml
- README.md
- recipe/meta.yaml
> sunpy 3.0.7

- .ci_support/osx_64_numpy1.19python3.7.____cpython.yaml
- .ci_support/osx_64_numpy1.19python3.8.____cpython.yaml
- .ci_support/osx_64_numpy1.19python3.9.____cpython.yaml
- .ci_support/osx_64_numpy1.21python3.10.____cpython.yaml
- recipe/meta.yaml
> sunpy 3.0.8

- .ci_support/osx_64_numpy1.19python3.7.____cpython.yaml
- .ci_support/osx_64_numpy1.19python3.8.____cpython.yaml
- .ci_support/osx_64_numpy1.19python3.9.____cpython.yaml
- .ci_support/osx_64_numpy1.21python3.10.____cpython.yaml
- .ci_support/osx_arm64_numpy1.19python3.8.____cpython.yaml
- .ci_support/osx_arm64_numpy1.19python3.9.____cpython.yaml
- .ci_support/osx_arm64_numpy1.21python3.10.____cpython.yaml
- recipe/meta.yaml
> sunpy 3.1.7

- .azure-pipelines/azure-pipelines-win.yml
- .circleci/config.yml
- .scripts/build_steps.sh
- .scripts/run_osx_build.sh
- LICENSE.txt
- build-locally.py
- recipe/meta.yaml
> Release 3.1.8

- .azure-pipelines/azure-pipelines-win.yml
- .ci_support/linux_64_numpy1.20python3.8.____cpython.yaml
- .ci_support/linux_64_numpy1.20python3.9.____cpython.yaml
- .ci_support/linux_64_numpy1.21python3.10.____cpython.yaml
- .ci_support/linux_64_numpy1.23python3.11.____cpython.yaml
- recipe/meta.yaml
> Update to 4.0.8

- recipe/meta.yaml
> updated v4.0.9

- recipe/meta.yaml
> sunpy 4.1.3

- recipe/meta.yaml
> 4.0.10 release

- .github/CODEOWNERS
- README.md
- recipe/meta.yaml
> Add myself back as maintainer

- .azure-pipelines/azure-pipelines-linux.yml
- .azure-pipelines/azure-pipelines-osx.yml
- .azure-pipelines/azure-pipelines-win.yml
- .ci_support/linux_64_numpy1.26python3.12.____cpython.yaml
- .ci_support/migrations/python312.yaml
- .ci_support/osx_64_numpy1.26python3.12.____cpython.yaml
- .ci_support/osx_arm64_numpy1.26python3.12.____cpython.yaml
- .ci_support/win_64_numpy1.26python3.12.____cpython.yaml
- .gitignore
- .scripts/build_steps.sh
- .scripts/run_docker_build.sh
- .scripts/run_osx_build.sh
- .scripts/run_win_build.bat
- README.md
- conda-forge.yml
- recipe/meta.yaml
> [5.0.x] 5.0.3 + py312

- .azure-pipelines/azure-pipelines-linux.yml
- .azure-pipelines/azure-pipelines-osx.yml
- .ci_support/linux_64_numpy1.22python3.10.____cpython.yaml
- .ci_support/linux_64_numpy1.22python3.9.____cpython.yaml
- .ci_support/linux_64_numpy1.23python3.11.____cpython.yaml
- .ci_support/linux_64_numpy1.26python3.12.____cpython.yaml
- .ci_support/osx_64_numpy1.22python3.10.____cpython.yaml
- .ci_support/osx_64_numpy1.22python3.9.____cpython.yaml
- .ci_support/osx_64_numpy1.23python3.11.____cpython.yaml
- .ci_support/osx_64_numpy1.26python3.12.____cpython.yaml
- .ci_support/osx_arm64_numpy1.22python3.10.____cpython.yaml
- .ci_support/osx_arm64_numpy1.22python3.9.____cpython.yaml
- .ci_support/osx_arm64_numpy1.23python3.11.____cpython.yaml
- .ci_support/osx_arm64_numpy1.26python3.12.____cpython.yaml
- .ci_support/win_64_numpy1.22python3.10.____cpython.yaml
- .ci_support/win_64_numpy1.22python3.9.____cpython.yaml
- .ci_support/win_64_numpy1.23python3.11.____cpython.yaml
- .ci_support/win_64_numpy1.26python3.12.____cpython.yaml
- .github/CODEOWNERS
- .scripts/build_steps.sh
- .scripts/run_osx_build.sh
- .scripts/run_win_build.bat
- README.md
- azure-pipelines.yml
- build-locally.py
- recipe/meta.yaml
> Remove myself as maintainer

- .azure-pipelines/azure-pipelines-linux.yml
- .azure-pipelines/azure-pipelines-osx.yml
- .azure-pipelines/azure-pipelines-win.yml
- .ci_support/linux_64_python3.10.____cpython.yaml
- .ci_support/linux_64_python3.11.____cpython.yaml
- .ci_support/linux_64_python3.12.____cpython.yaml
- .ci_support/linux_aarch64_python3.10.____cpython.yaml
- .ci_support/linux_aarch64_python3.11.____cpython.yaml
- .ci_support/linux_aarch64_python3.12.____cpython.yaml
- .ci_support/osx_64_python3.10.____cpython.yaml
- .ci_support/osx_64_python3.11.____cpython.yaml
- .ci_support/osx_64_python3.12.____cpython.yaml
- .ci_support/osx_arm64_python3.10.____cpython.yaml
- .ci_support/osx_arm64_python3.11.____cpython.yaml
- .ci_support/osx_arm64_python3.12.____cpython.yaml
- .scripts/build_steps.sh
- .scripts/run_osx_build.sh
- .scripts/run_win_build.bat
- README.md
- azure-pipelines.yml
- build-locally.py
- conda-forge.yml
- recipe/meta.yaml
- recipe/run_test.py
> Add emulated aarch64 builds and re-render
